// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: front.proto

package front

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceFrontendAPI_FetchStatusJSON_FullMethodName = "/front.ServiceFrontendAPI/FetchStatusJSON"
)

// ServiceFrontendAPIClient is the client API for ServiceFrontendAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceFrontendAPIClient interface {
	FetchStatusJSON(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusJSON, error)
}

type serviceFrontendAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceFrontendAPIClient(cc grpc.ClientConnInterface) ServiceFrontendAPIClient {
	return &serviceFrontendAPIClient{cc}
}

func (c *serviceFrontendAPIClient) FetchStatusJSON(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusJSON, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusJSON)
	err := c.cc.Invoke(ctx, ServiceFrontendAPI_FetchStatusJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceFrontendAPIServer is the server API for ServiceFrontendAPI service.
// All implementations must embed UnimplementedServiceFrontendAPIServer
// for forward compatibility.
type ServiceFrontendAPIServer interface {
	FetchStatusJSON(context.Context, *emptypb.Empty) (*StatusJSON, error)
	mustEmbedUnimplementedServiceFrontendAPIServer()
}

// UnimplementedServiceFrontendAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceFrontendAPIServer struct{}

func (UnimplementedServiceFrontendAPIServer) FetchStatusJSON(context.Context, *emptypb.Empty) (*StatusJSON, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchStatusJSON not implemented")
}
func (UnimplementedServiceFrontendAPIServer) mustEmbedUnimplementedServiceFrontendAPIServer() {}
func (UnimplementedServiceFrontendAPIServer) testEmbeddedByValue()                            {}

// UnsafeServiceFrontendAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceFrontendAPIServer will
// result in compilation errors.
type UnsafeServiceFrontendAPIServer interface {
	mustEmbedUnimplementedServiceFrontendAPIServer()
}

func RegisterServiceFrontendAPIServer(s grpc.ServiceRegistrar, srv ServiceFrontendAPIServer) {
	// If the following call pancis, it indicates UnimplementedServiceFrontendAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceFrontendAPI_ServiceDesc, srv)
}

func _ServiceFrontendAPI_FetchStatusJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceFrontendAPIServer).FetchStatusJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceFrontendAPI_FetchStatusJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceFrontendAPIServer).FetchStatusJSON(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceFrontendAPI_ServiceDesc is the grpc.ServiceDesc for ServiceFrontendAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceFrontendAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "front.ServiceFrontendAPI",
	HandlerType: (*ServiceFrontendAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchStatusJSON",
			Handler:    _ServiceFrontendAPI_FetchStatusJSON_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "front.proto",
}
